
#!/usr/bin/env bash
set -euo pipefail
[ -f .env ] || { echo ".env not found"; exit 1; }
set -a; source .env; set +a
: "${WAN_IFACE:?}"; : "${PXE_IFACE:?}"

RULES_FILE=/etc/nftables.d/sit-nat.nft
UNIT_FILE=/etc/systemd/system/sit-nat.service
SYSCTL_FILE=/etc/sysctl.d/99-sit-nat.conf

sudo mkdir -p /etc/nftables.d

cat <<EOF | sudo tee "$RULES_FILE" >/dev/null
# Generated by persist-nat-nftables.sh
flush table inet sit_nat

table inet sit_nat {
  chain postrouting {
    type nat hook postrouting priority 100; policy accept;
    oifname "${WAN_IFACE}" masquerade
  }
  chain forward {
    type filter hook forward priority 0; policy drop;
    iifname "${PXE_IFACE}" oifname "${WAN_IFACE}" accept
    iifname "${WAN_IFACE}" oifname "${PXE_IFACE}" ct state related,established accept
  }
}
EOF

cat <<'EOF' | sudo tee "$UNIT_FILE" >/dev/null
[Unit]
Description=SIT NAT (MASQUERADE) via nftables
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
ExecStart=/usr/sbin/nft -f /etc/nftables.d/sit-nat.nft
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
EOF

# Enable IPv4 forwarding persistently
cat <<EOF | sudo tee "$SYSCTL_FILE" >/dev/null
net.ipv4.ip_forward=1
EOF

sudo sysctl --system >/dev/null

# Apply once immediately; then enable unit for boot
if command -v nft >/dev/null 2>&1; then
  sudo nft -f "$RULES_FILE"
else
  echo "WARNING: nft command not found. Please install nftables package."
fi

sudo systemctl daemon-reload
sudo systemctl enable --now sit-nat.service

echo "Persistent NAT configured via nftables. Rules in $RULES_FILE; unit $UNIT_FILE."
