"""Slurm cluster builder: generate slurm.conf/gres.conf from discovered
hardware and produce the built-in Ansible deployment playbook.

Everything here is pure text generation (unit-testable with no nodes);
execution goes through the existing Ansible/SSH job engine. Scope: Ubuntu /
Debian nodes using the distro slurm-wlm packages — deliberate, documented,
and visible to the operator because the playbook itself lands in the job log.

NodeAddr is always emitted so the cluster works without DNS or /etc/hosts
coordination, and daemon identity never depends on a box's OS hostname
matching its CCP inventory name (they differ until the one-click rename):

- slurmd is pinned to its NodeName with `slurmd -N <name>` via a
  SLURMD_OPTIONS systemd drop-in (else: "Unable to determine this slurmd's
  NodeName" on a box still called e.g. 'gpu-node');
- the SlurmctldHost *name* is resolved to the controller's real hostname from
  Ansible facts at deploy time (else slurmctld refuses to start with "This
  host ... not a valid controller"); the (address) part is kept for
  communication.
"""

import json

MEM_RESERVE_MB = 512      # keep a slice for the OS so slurmd doesn't overcommit


def _gpu_declarable(hw):
    """True when a node's GPUs were seen *through the driver* (nvidia-smi), so
    the /dev/nvidia* device files exist and a File= gres entry is safe.

    Hardware discovery also counts GPUs from lspci when nvidia-smi is missing —
    i.e. the card is present but the driver is not loaded. Declaring those to
    Slurm is actively harmful: slurmd blocks with "Waiting for gres.conf file
    /dev/nvidia0" and the node never registers. (A file-less Count= entry is
    not an alternative — Slurm drops it: "Ignoring file-less GPU".)"""
    if not hw:
        return False
    raw = hw.get('raw_json')
    if raw is None:          # summary-only dict (no facts payload) — trust the count
        return True
    try:
        data = json.loads(raw) if isinstance(raw, str) else raw
    except (ValueError, TypeError):
        return True
    if 'gpu' in data:        # nvidia-smi answered → driver loaded → devices exist
        return True
    if 'pci_gpu' in data:    # only the PCI bus saw them → no driver
        return False
    return True


def _node_line(node, hw, gpus=None):
    """One NodeName= line. Falls back to CPUs=1 RealMemory=256 when hardware
    was never scanned (the operator sees the warning from generate()).
    `gpus` is the effective, declarable GPU count decided by generate()."""
    parts = [f'NodeName={node["name"]}', f'NodeAddr={node["address"]}']
    cores = (hw or {}).get('cpu_cores') or 0
    if cores:
        parts.append(f'CPUs={cores}')
        sockets = (hw or {}).get('cpu_sockets')
        tpc = (hw or {}).get('threads_per_core')
        # emit the full geometry only when it is self-consistent
        if sockets and tpc and cores % (sockets * tpc) == 0:
            parts.append(f'Sockets={sockets}')
            parts.append(f'CoresPerSocket={cores // (sockets * tpc)}')
            parts.append(f'ThreadsPerCore={tpc}')
    else:
        parts.append('CPUs=1')
    mem = (hw or {}).get('mem_mb') or 0
    parts.append(f'RealMemory={max(mem - MEM_RESERVE_MB, 256)}')
    if gpus is None:
        gpus = (hw or {}).get('gpu_count') or 0
    if gpus:
        parts.append(f'Gres=gpu:{gpus}')
    parts.append('State=UNKNOWN')
    return ' '.join(parts)


def generate(cluster_name, members, controller, hardware_by_node):
    """Build (slurm_conf, gres_conf, warnings).

    members: node rows (managed members, controller included — lab clusters
    typically run slurmd on the controller too). controller: node row.
    hardware_by_node: {node_id: hardware row or None}."""
    warnings = []
    node_lines, gres_lines = [], []
    any_gpu = False
    for n in members:
        hw = hardware_by_node.get(n['id'])
        if not hw or not hw.get('cpu_cores'):
            warnings.append(f'{n["name"]}: no hardware facts — using minimal '
                            'defaults (run a hardware scan and regenerate)')
        gpus = (hw or {}).get('gpu_count') or 0
        if gpus and not _gpu_declarable(hw):
            warnings.append(
                f'{n["name"]}: {gpus} GPU(s) seen on the PCI bus but the NVIDIA '
                'driver is not loaded, so /dev/nvidia* does not exist. Not '
                'declaring them to Slurm — slurmd would hang waiting for the '
                'device files and the node would never come up. Install the '
                'driver, rescan the hardware, then regenerate.')
            gpus = 0
        node_lines.append(_node_line(n, hw, gpus))
        if gpus:
            any_gpu = True
            dev = ('/dev/nvidia0' if gpus == 1
                   else f'/dev/nvidia[0-{gpus - 1}]')
            gres_lines.append(f'NodeName={n["name"]} Name=gpu File={dev}')

    conf = [
        f'# generated by CCP for cluster {cluster_name} — regenerate from the',
        '# Clusters page after hardware or membership changes',
        f'ClusterName={cluster_name}',
        f'SlurmctldHost={controller["name"]}({controller["address"]})',
        'AuthType=auth/munge',
        'SlurmUser=slurm',
        'SlurmctldPort=6817',
        'SlurmdPort=6818',
        'StateSaveLocation=/var/spool/slurmctld',
        'SlurmdSpoolDir=/var/spool/slurmd',
        'SlurmctldPidFile=/run/slurmctld.pid',
        'SlurmdPidFile=/run/slurmd.pid',
        'SlurmctldLogFile=/var/log/slurm/slurmctld.log',
        'SlurmdLogFile=/var/log/slurm/slurmd.log',
        # linuxproc/none keep the deploy free of cgroup.conf coordination —
        # good lab defaults, tighten later if needed
        'ProctrackType=proctrack/linuxproc',
        'TaskPlugin=task/none',
        # slurm's default MailProg (/bin/mail) doesn't exist on minimal
        # Ubuntu/Debian and logs an error at every daemon start
        'MailProg=/bin/true',
        'MpiDefault=none',
        'ReturnToService=2',
        'SchedulerType=sched/backfill',
        'SelectType=select/cons_tres',
        'SelectTypeParameters=CR_Core_Memory',
    ]
    if any_gpu:
        conf.append('GresTypes=gpu')
    conf.append('')
    conf += node_lines
    names = ','.join(n['name'] for n in members)
    conf.append(f'PartitionName=main Nodes={names} Default=YES '
                'MaxTime=INFINITE State=UP')
    gres = ('# generated by CCP — GPU devices per node\n'
            + '\n'.join(gres_lines) + '\n') if gres_lines else ''
    return '\n'.join(conf) + '\n', gres, warnings


def _yaml_block(text, indent):
    """Indent config text as a YAML literal block scalar body."""
    pad = ' ' * indent
    return '\n'.join(pad + line for line in text.splitlines())


def _resolve_slurmctld_host(slurm_conf):
    """Rewrite the SlurmctldHost *name* to the controller's real OS hostname,
    resolved from Ansible facts at deploy time.

    slurmctld refuses to start ("This host ... not a valid controller") unless
    the name part of SlurmctldHost equals the machine's own `hostname -s` —
    and a box's hostname can differ from its CCP inventory name (e.g. a
    controller still called 'ubuntu-amd64-lab'). The name part exists only for
    that self-identification; every daemon reaches the controller through the
    (address) part, which is kept verbatim."""
    out = []
    for line in slurm_conf.splitlines():
        if line.startswith('SlurmctldHost='):
            addr = line[line.index('('):] if '(' in line else ''
            line = ("SlurmctldHost="
                    "{{ hostvars[slurm_controller]['ansible_hostname'] }}" + addr)
        out.append(line)
    return '\n'.join(out) + '\n'


def deploy_playbook(slurm_conf, gres_conf, controller_name,
                    reinstall=False, version=None):
    """The built-in deployment playbook (Ubuntu/Debian slurm-wlm): munge key
    generated on the controller and distributed to every node, configs pushed,
    spool dirs created, slurmctld on the controller and slurmd everywhere.
    The generated configs are inlined so the playbook in the job log is the
    complete, auditable record of what was deployed. The SlurmctldHost name is
    resolved to the controller's real hostname at deploy time (see
    _resolve_slurmctld_host); slurmd identity is pinned with -N.

    reinstall=True purges the installed Slurm/munge packages and all of their
    config and state first, then installs again — the way out of a fleet that
    drifted onto incompatible versions or a half-configured install.
    version pins the apt version (e.g. '23.11.4-1.2ubuntu5'), which is what
    actually converges a mixed fleet; it must exist in every node's sources."""
    slurm_conf = _resolve_slurmctld_host(slurm_conf)
    gres_task = ''
    if gres_conf:
        gres_task = f'''
    - name: Write gres.conf
      ansible.builtin.copy:
        dest: /etc/slurm/gres.conf
        owner: root
        mode: "0644"
        content: |
{_yaml_block(gres_conf, 10)}
'''
    # Optional clean slate: purge the installed Slurm/munge and every scrap of
    # their config and state before installing again. Used to escape a fleet
    # that drifted onto different versions, or a half-configured install.
    purge_tasks = '' if not reinstall else '''
    - name: Stop Slurm and munge before the clean reinstall
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
      loop: [slurmd, slurmctld, munge]
      failed_when: false

    - name: Purge the installed Slurm and munge packages
      ansible.builtin.apt:
        name:
          - slurm-wlm
          - slurm-wlm-basic-plugins
          - slurm-client
          - slurmd
          - slurmctld
          - munge
        state: absent
        purge: true
        autoremove: true

    - name: Remove leftover Slurm and munge config and state
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/slurm
        - /etc/slurm-llnl
        - /etc/munge
        - /var/spool/slurmctld
        - /var/spool/slurmd
        - /var/log/slurm
        - /etc/systemd/system/slurmd.service.d/10-ccp-nodename.conf
'''
    # An exact version pin is what actually converges a drifted fleet — but the
    # pinned version has to exist in every node's apt sources.
    pkg = 'slurm-wlm' if not version else f'slurm-wlm={version}'
    pin_opts = '' if not version else '        allow_downgrade: true\n'
    install_name = ('Install munge and slurm-wlm' if not version
                    else f'Install munge and slurm-wlm pinned to {version}')

    # Without a pin, `apt install slurm-wlm` leaves an already-installed node
    # exactly as it was — so mismatched versions can only be rejected, not
    # fixed. With a pin, the install converges them, so that gate is skipped
    # and replaced by a check that the pin is actually installable everywhere.
    gate_when = 'false' if version else 'true'
    pin_gate = '' if not version else f'''
    - name: Start the pin-availability check
      run_once: true
      ansible.builtin.set_fact:
        slurm_pin_missing: []

    - name: Collect nodes whose apt sources lack the pinned version
      run_once: true
      ansible.builtin.set_fact:
        slurm_pin_missing: "{{{{ slurm_pin_missing + [item] }}}}"
      loop: "{{{{ ansible_play_hosts }}}}"
      when: >-
        '{version}' not in (hostvars[item]['slurm_avail']['stdout_lines']
                            | default([]))

    - name: Fail when the pinned version cannot be installed everywhere
      run_once: true
      ansible.builtin.assert:
        that:
          - slurm_pin_missing | length == 0
        success_msg: "{version} is installable on every node"
        fail_msg: |
          Pinned version {version} is not in the apt sources of:
          {{% for h in slurm_pin_missing %}}  {{{{ h }}}} — offers: {{{{ hostvars[h]['slurm_avail']['stdout_lines'] | default([]) | join(', ') | default('(none)', true) }}}}
          {{% endfor %}}
          Versions available on EVERY node:
            {{{{ slurm_common | default([]) | reverse | list | join('  ') | default('(none — the nodes are on different Ubuntu releases)', true) }}}}
          Nothing was changed on any node.
'''

    return f'''---
- name: Deploy Slurm (CCP built-in, Ubuntu/Debian slurm-wlm)
  hosts: all
  become: true
  gather_facts: true          # ansible_hostname feeds SlurmctldHost below
  vars:
    slurm_controller: {controller_name}
  tasks:
    # ── read-only preflight ───────────────────────────────────────────────
    # Everything that can reject this deploy runs BEFORE anything is changed.
    # Gating after a purge once left nodes with slurm-wlm installed, slurmd
    # enabled and /etc/slurm deleted — slurmd then falls back to configless
    # mode and loops on "resolve_ctls_from_dns_srv: Unknown host" forever.
    - name: Refresh the apt cache
      ansible.builtin.apt:
        update_cache: true
      changed_when: false

    - name: Record the installed Slurm version
      ansible.builtin.command: slurmd -V
      register: slurm_ver
      changed_when: false
      failed_when: false          # not installed yet is a valid starting point

    # Which versions each node could install. Without this the operator has to
    # guess what to type into "Pin version" — and a pin that is missing on one
    # node just fails the apt task with no hint of what would have worked.
    - name: List the Slurm versions this node's apt sources offer
      ansible.builtin.shell: |
        set -o pipefail
        apt-cache madison slurm-wlm 2>/dev/null \
          | awk -F'|' '{{gsub(/ /, "", $2); print $2}}' | sort -Vu
      args:
        executable: /bin/bash
      register: slurm_avail
      changed_when: false
      failed_when: false

    - name: Seed the cluster-wide version candidate list
      run_once: true
      ansible.builtin.set_fact:
        slurm_common: "{{{{ hostvars[ansible_play_hosts[0]]['slurm_avail']['stdout_lines']
                        | default([]) }}}}"

    - name: Reduce it to versions available on every node
      run_once: true
      ansible.builtin.set_fact:
        slurm_common: "{{{{ slurm_common
                        | intersect(hostvars[item]['slurm_avail']['stdout_lines']
                        | default([])) }}}}"
      loop: "{{{{ ansible_play_hosts[1:] }}}}"

{pin_gate}
    - name: Fail fast when Slurm versions differ across the cluster
      run_once: true
      when: {gate_when}
      ansible.builtin.assert:
        that:
          - ansible_play_hosts | map('extract', hostvars, ['slurm_ver', 'stdout'])
            | map('trim') | unique | list | length == 1
        success_msg: "every node runs {{{{ slurm_ver.stdout | trim }}}}"
        fail_msg: |
          Slurm versions differ across this cluster, so the nodes will never
          register with the controller.

          Installed now:
          {{% for h in ansible_play_hosts %}}  {{{{ h }}}}: {{{{ hostvars[h]['slurm_ver']['stdout'] | trim }}}}
          {{% endfor %}}
          Offered by each node's apt sources:
          {{% for h in ansible_play_hosts %}}  {{{{ h }}}}: {{{{ hostvars[h]['slurm_avail']['stdout_lines'] | default([]) | join(', ') | default('(none)', true) }}}}
          {{% endfor %}}
          {{% if slurm_common | default([]) | length > 0 %}}
          WHAT TO DO: these versions exist on EVERY node — put one in
          "Pin version" (newest first) and tick "Clean reinstall", then Deploy:
            {{{{ slurm_common | reverse | list | join('  ') }}}}
          {{% else %}}
          WHAT TO DO: there is NO version available on every node, so pinning
          cannot work here — each Ubuntu release ships only its own Slurm.
          Reinstall the odd node(s) so every node runs the same Ubuntu release
          (that is what this PXE platform is for), re-onboard from Discovery,
          then Deploy. Alternatively serve one common Slurm build from your own
          apt repo / .deb on every node.
          {{% endif %}}

    # ── from here on the node is modified ─────────────────────────────────
{purge_tasks}
    - name: {install_name}
      ansible.builtin.apt:
        name: [munge, {pkg}]
        state: present
{pin_opts}
    # The package enables (and on a real host starts) slurmd immediately. Hold
    # both daemons down until their config exists, so slurmd can never run
    # configless and spam DNS SRV lookups; they are enabled again at the end.
    - name: Hold Slurm daemons down until the config is in place
      ansible.builtin.systemd:
        name: "{{{{ item }}}}"
        state: stopped
      loop: [slurmd, slurmctld]
      failed_when: false

    - name: Re-read the Slurm version after installing
      ansible.builtin.command: slurmd -V
      register: slurm_ver_after
      changed_when: false

    - name: Confirm every node ended up on the same Slurm version
      run_once: true
      ansible.builtin.assert:
        that:
          - ansible_play_hosts | map('extract', hostvars, ['slurm_ver_after', 'stdout'])
            | map('trim') | unique | list | length == 1
        success_msg: "every node runs {{{{ slurm_ver_after.stdout | trim }}}}"
        fail_msg: |
          The nodes still run different Slurm versions after installing:
          {{% for h in ansible_play_hosts %}}  {{{{ h }}}}: {{{{ hostvars[h]['slurm_ver_after']['stdout'] | trim }}}}
          {{% endfor %}}
          Nothing further was configured, and the daemons are left stopped
          rather than half-configured.

    - name: Generate the munge key on the controller
      ansible.builtin.command:
        cmd: /usr/sbin/mungekey --create --force
        creates: /etc/munge/munge.key
      when: inventory_hostname == slurm_controller

    - name: Read the controller munge key
      ansible.builtin.slurp:
        src: /etc/munge/munge.key
      register: munge_key
      delegate_to: "{{{{ slurm_controller }}}}"
      run_once: true

    - name: Distribute the munge key
      ansible.builtin.copy:
        dest: /etc/munge/munge.key
        content: "{{{{ munge_key.content | b64decode }}}}"
        owner: munge
        group: munge
        mode: "0400"

    - name: Restart munge
      ansible.builtin.systemd:
        name: munge
        state: restarted
        enabled: true

    - name: Ensure config and spool directories
      ansible.builtin.file:
        path: "{{{{ item.path }}}}"
        state: directory
        owner: "{{{{ item.owner }}}}"
        mode: "0755"
      loop:
        - {{ path: /etc/slurm, owner: root }}
        - {{ path: /var/spool/slurmd, owner: slurm }}
        - {{ path: /var/log/slurm, owner: slurm }}

    - name: Ensure controller state directory
      ansible.builtin.file:
        path: /var/spool/slurmctld
        state: directory
        owner: slurm
        mode: "0755"
      when: inventory_hostname == slurm_controller

    # Every node resolving every other node by name is what MPI, srun and
    # most HPC tooling expect (slurm.conf itself uses NodeAddr, so this is not
    # what makes Slurm work — it is what makes jobs on it work). Kept inside
    # CCP markers so membership changes rewrite the block instead of appending.
    - name: Maintain the CCP-managed cluster peer entries in /etc/hosts
      ansible.builtin.blockinfile:
        path: /etc/hosts
        marker: "# {{mark}} CCP CLUSTER HOSTS"
        block: |
          {{% for h in ansible_play_hosts %}}
          {{{{ hostvars[h].ansible_host | default(h, true) }}}} {{{{ h }}}}
          {{% endfor %}}

    - name: Write slurm.conf
      ansible.builtin.copy:
        dest: /etc/slurm/slurm.conf
        owner: root
        mode: "0644"
        content: |
{_yaml_block(slurm_conf, 10)}
{gres_task}
    - name: Start slurmctld on the controller
      ansible.builtin.systemd:
        name: slurmctld
        state: restarted
        enabled: true
      when: inventory_hostname == slurm_controller

    # The slurm-wlm package enables slurmctld on every node, so non-controller
    # boxes show a permanently-failed slurmctld ("not a valid controller").
    # Stop and disable it there so `systemctl status` and logs stay clean and
    # it never fights slurmd for attention.
    - name: Disable slurmctld on non-controller nodes
      ansible.builtin.systemd:
        name: slurmctld
        state: stopped
        enabled: false
      when: inventory_hostname != slurm_controller
      failed_when: false

    # Pin each slurmd's NodeName explicitly. Without this, slurmd identifies
    # itself by matching the machine's OS hostname against a NodeName line in
    # slurm.conf and aborts with "Unable to determine this slurmd's NodeName"
    # whenever the box hostname differs from its CCP inventory name (e.g. a
    # node still called 'gpu-node'). inventory_hostname IS the NodeName here,
    # so -N makes slurmd's identity independent of the OS hostname.
    - name: Ensure the slurmd systemd drop-in directory
      ansible.builtin.file:
        path: /etc/systemd/system/slurmd.service.d
        state: directory
        mode: "0755"

    - name: Force slurmd's NodeName (SLURMD_OPTIONS)
      ansible.builtin.copy:
        dest: /etc/systemd/system/slurmd.service.d/10-ccp-nodename.conf
        mode: "0644"
        content: |
          [Service]
          Environment=SLURMD_OPTIONS=-N {{{{ inventory_hostname }}}}

    - name: Start slurmd on every node
      ansible.builtin.systemd:
        name: slurmd
        state: restarted
        enabled: true
        daemon_reload: true
'''


def cleanup_playbook():
    """Teardown / recovery: stop and DISABLE the daemons, then remove
    everything CCP put on the node. Packages are left installed (safe to
    re-deploy; removing them is an operator decision).

    This is also the way out of a node whose slurmd is enabled but has no
    config: without slurm.conf, slurmd falls back to configless mode and loops
    on "resolve_ctls_from_dns_srv: Unknown host" — disabling it stops that."""
    return '''---
- name: Slurm cleanup (CCP built-in)
  hosts: all
  become: true
  tasks:
    - name: Stop and disable slurm services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
        enabled: false
      loop: [slurmd, slurmctld]
      failed_when: false

    - name: Remove generated configs
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/slurm/slurm.conf
        - /etc/slurm/gres.conf
        - /etc/systemd/system/slurmd.service.d/10-ccp-nodename.conf

    - name: Remove the CCP-managed cluster peer entries from /etc/hosts
      ansible.builtin.blockinfile:
        path: /etc/hosts
        marker: "# {mark} CCP CLUSTER HOSTS"
        state: absent
      failed_when: false

    - name: Reload systemd after removing the drop-in
      ansible.builtin.systemd:
        daemon_reload: true
      failed_when: false
'''
