"""Slurm cluster builder: generate slurm.conf/gres.conf from discovered
hardware and produce the built-in Ansible deployment playbook.

Everything here is pure text generation (unit-testable with no nodes);
execution goes through the existing Ansible/SSH job engine. Scope: Ubuntu /
Debian nodes using the distro slurm-wlm packages — deliberate, documented,
and visible to the operator because the playbook itself lands in the job log.

NodeAddr is always emitted so the cluster works without DNS or /etc/hosts
coordination, and daemon identity never depends on a box's OS hostname
matching its CCP inventory name (they differ until the one-click rename):

- slurmd is pinned to its NodeName with `slurmd -N <name>` via a
  SLURMD_OPTIONS systemd drop-in (else: "Unable to determine this slurmd's
  NodeName" on a box still called e.g. 'gpu-node');
- the SlurmctldHost *name* is resolved to the controller's real hostname from
  Ansible facts at deploy time (else slurmctld refuses to start with "This
  host ... not a valid controller"); the (address) part is kept for
  communication.
"""

MEM_RESERVE_MB = 512      # keep a slice for the OS so slurmd doesn't overcommit


def _node_line(node, hw):
    """One NodeName= line. Falls back to CPUs=1 RealMemory=256 when hardware
    was never scanned (the operator sees the warning from generate())."""
    parts = [f'NodeName={node["name"]}', f'NodeAddr={node["address"]}']
    cores = (hw or {}).get('cpu_cores') or 0
    if cores:
        parts.append(f'CPUs={cores}')
        sockets = (hw or {}).get('cpu_sockets')
        tpc = (hw or {}).get('threads_per_core')
        # emit the full geometry only when it is self-consistent
        if sockets and tpc and cores % (sockets * tpc) == 0:
            parts.append(f'Sockets={sockets}')
            parts.append(f'CoresPerSocket={cores // (sockets * tpc)}')
            parts.append(f'ThreadsPerCore={tpc}')
    else:
        parts.append('CPUs=1')
    mem = (hw or {}).get('mem_mb') or 0
    parts.append(f'RealMemory={max(mem - MEM_RESERVE_MB, 256)}')
    gpus = (hw or {}).get('gpu_count') or 0
    if gpus:
        parts.append(f'Gres=gpu:{gpus}')
    parts.append('State=UNKNOWN')
    return ' '.join(parts)


def generate(cluster_name, members, controller, hardware_by_node):
    """Build (slurm_conf, gres_conf, warnings).

    members: node rows (managed members, controller included — lab clusters
    typically run slurmd on the controller too). controller: node row.
    hardware_by_node: {node_id: hardware row or None}."""
    warnings = []
    node_lines, gres_lines = [], []
    any_gpu = False
    for n in members:
        hw = hardware_by_node.get(n['id'])
        if not hw or not hw.get('cpu_cores'):
            warnings.append(f'{n["name"]}: no hardware facts — using minimal '
                            'defaults (run a hardware scan and regenerate)')
        node_lines.append(_node_line(n, hw))
        gpus = (hw or {}).get('gpu_count') or 0
        if gpus:
            any_gpu = True
            dev = ('/dev/nvidia0' if gpus == 1
                   else f'/dev/nvidia[0-{gpus - 1}]')
            gres_lines.append(f'NodeName={n["name"]} Name=gpu File={dev}')

    conf = [
        f'# generated by CCP for cluster {cluster_name} — regenerate from the',
        '# Clusters page after hardware or membership changes',
        f'ClusterName={cluster_name}',
        f'SlurmctldHost={controller["name"]}({controller["address"]})',
        'AuthType=auth/munge',
        'SlurmUser=slurm',
        'SlurmctldPort=6817',
        'SlurmdPort=6818',
        'StateSaveLocation=/var/spool/slurmctld',
        'SlurmdSpoolDir=/var/spool/slurmd',
        'SlurmctldPidFile=/run/slurmctld.pid',
        'SlurmdPidFile=/run/slurmd.pid',
        'SlurmctldLogFile=/var/log/slurm/slurmctld.log',
        'SlurmdLogFile=/var/log/slurm/slurmd.log',
        # linuxproc/none keep the deploy free of cgroup.conf coordination —
        # good lab defaults, tighten later if needed
        'ProctrackType=proctrack/linuxproc',
        'TaskPlugin=task/none',
        # slurm's default MailProg (/bin/mail) doesn't exist on minimal
        # Ubuntu/Debian and logs an error at every daemon start
        'MailProg=/bin/true',
        'MpiDefault=none',
        'ReturnToService=2',
        'SchedulerType=sched/backfill',
        'SelectType=select/cons_tres',
        'SelectTypeParameters=CR_Core_Memory',
    ]
    if any_gpu:
        conf.append('GresTypes=gpu')
    conf.append('')
    conf += node_lines
    names = ','.join(n['name'] for n in members)
    conf.append(f'PartitionName=main Nodes={names} Default=YES '
                'MaxTime=INFINITE State=UP')
    gres = ('# generated by CCP — GPU devices per node\n'
            + '\n'.join(gres_lines) + '\n') if gres_lines else ''
    return '\n'.join(conf) + '\n', gres, warnings


def _yaml_block(text, indent):
    """Indent config text as a YAML literal block scalar body."""
    pad = ' ' * indent
    return '\n'.join(pad + line for line in text.splitlines())


def _resolve_slurmctld_host(slurm_conf):
    """Rewrite the SlurmctldHost *name* to the controller's real OS hostname,
    resolved from Ansible facts at deploy time.

    slurmctld refuses to start ("This host ... not a valid controller") unless
    the name part of SlurmctldHost equals the machine's own `hostname -s` —
    and a box's hostname can differ from its CCP inventory name (e.g. a
    controller still called 'ubuntu-amd64-lab'). The name part exists only for
    that self-identification; every daemon reaches the controller through the
    (address) part, which is kept verbatim."""
    out = []
    for line in slurm_conf.splitlines():
        if line.startswith('SlurmctldHost='):
            addr = line[line.index('('):] if '(' in line else ''
            line = ("SlurmctldHost="
                    "{{ hostvars[slurm_controller]['ansible_hostname'] }}" + addr)
        out.append(line)
    return '\n'.join(out) + '\n'


def deploy_playbook(slurm_conf, gres_conf, controller_name):
    """The built-in deployment playbook (Ubuntu/Debian slurm-wlm): munge key
    generated on the controller and distributed to every node, configs pushed,
    spool dirs created, slurmctld on the controller and slurmd everywhere.
    The generated configs are inlined so the playbook in the job log is the
    complete, auditable record of what was deployed. The SlurmctldHost name is
    resolved to the controller's real hostname at deploy time (see
    _resolve_slurmctld_host); slurmd identity is pinned with -N."""
    slurm_conf = _resolve_slurmctld_host(slurm_conf)
    gres_task = ''
    if gres_conf:
        gres_task = f'''
    - name: Write gres.conf
      ansible.builtin.copy:
        dest: /etc/slurm/gres.conf
        owner: root
        mode: "0644"
        content: |
{_yaml_block(gres_conf, 10)}
'''
    return f'''---
- name: Deploy Slurm (CCP built-in, Ubuntu/Debian slurm-wlm)
  hosts: all
  become: true
  vars:
    slurm_controller: {controller_name}
  tasks:
    - name: Install munge and slurm-wlm
      ansible.builtin.apt:
        name: [munge, slurm-wlm]
        state: present
        update_cache: true

    - name: Generate the munge key on the controller
      ansible.builtin.command:
        cmd: /usr/sbin/mungekey --create --force
        creates: /etc/munge/munge.key
      when: inventory_hostname == slurm_controller

    - name: Read the controller munge key
      ansible.builtin.slurp:
        src: /etc/munge/munge.key
      register: munge_key
      delegate_to: "{{{{ slurm_controller }}}}"
      run_once: true

    - name: Distribute the munge key
      ansible.builtin.copy:
        dest: /etc/munge/munge.key
        content: "{{{{ munge_key.content | b64decode }}}}"
        owner: munge
        group: munge
        mode: "0400"

    - name: Restart munge
      ansible.builtin.systemd:
        name: munge
        state: restarted
        enabled: true

    - name: Ensure config and spool directories
      ansible.builtin.file:
        path: "{{{{ item.path }}}}"
        state: directory
        owner: "{{{{ item.owner }}}}"
        mode: "0755"
      loop:
        - {{ path: /etc/slurm, owner: root }}
        - {{ path: /var/spool/slurmd, owner: slurm }}
        - {{ path: /var/log/slurm, owner: slurm }}

    - name: Ensure controller state directory
      ansible.builtin.file:
        path: /var/spool/slurmctld
        state: directory
        owner: slurm
        mode: "0755"
      when: inventory_hostname == slurm_controller

    - name: Write slurm.conf
      ansible.builtin.copy:
        dest: /etc/slurm/slurm.conf
        owner: root
        mode: "0644"
        content: |
{_yaml_block(slurm_conf, 10)}
{gres_task}
    - name: Start slurmctld on the controller
      ansible.builtin.systemd:
        name: slurmctld
        state: restarted
        enabled: true
      when: inventory_hostname == slurm_controller

    # Pin each slurmd's NodeName explicitly. Without this, slurmd identifies
    # itself by matching the machine's OS hostname against a NodeName line in
    # slurm.conf and aborts with "Unable to determine this slurmd's NodeName"
    # whenever the box hostname differs from its CCP inventory name (e.g. a
    # node still called 'gpu-node'). inventory_hostname IS the NodeName here,
    # so -N makes slurmd's identity independent of the OS hostname.
    - name: Ensure the slurmd systemd drop-in directory
      ansible.builtin.file:
        path: /etc/systemd/system/slurmd.service.d
        state: directory
        mode: "0755"

    - name: Force slurmd's NodeName (SLURMD_OPTIONS)
      ansible.builtin.copy:
        dest: /etc/systemd/system/slurmd.service.d/10-ccp-nodename.conf
        mode: "0644"
        content: |
          [Service]
          Environment=SLURMD_OPTIONS=-N {{{{ inventory_hostname }}}}

    - name: Start slurmd on every node
      ansible.builtin.systemd:
        name: slurmd
        state: restarted
        enabled: true
        daemon_reload: true
'''


def cleanup_playbook():
    """Teardown: stop and disable services, remove the configs. Packages are
    left installed (safe to re-deploy; removal is an operator decision)."""
    return '''---
- name: Slurm cleanup (CCP built-in)
  hosts: all
  become: true
  tasks:
    - name: Stop and disable slurm services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
        enabled: false
      loop: [slurmd, slurmctld]
      failed_when: false

    - name: Remove generated configs
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop: [/etc/slurm/slurm.conf, /etc/slurm/gres.conf]
'''
